alias mmc='make MENUCONFIG_COLOR=blackbg menuconfig'
alias mkmc='make MENUCONFIG_COLOR=blackbg kernel_menuconfig'
alias mkl='make target/linux/compile'
alias wtime='last reboot | head -7; uptime'
alias lla='ls -la'
alias llh='ls -lh'
alias llah='ls -lah'
alias cal='ncal -bM'
alias :e='nvim'
alias vd='cd $(vifm ./ --choose-dir -)'
